In [52]:
%matplotlib widget
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import os, sys
import glob

In [53]:
dictflag = {'Caso':['Full','Segmented rectangular','Segmented Triangular'],'f_bistable':np.zeros((3)),'f_flutter':np.zeros((3)),'U_bistable':np.zeros((3)),'U_flutter':np.zeros((3))}
A = pd.DataFrame.from_dict(dictflag)

In [105]:
A.iloc[0,1] = 11.9
A.iloc[0,2]= 16.3
A.iloc[1,1] = 16.6
A.iloc[1,2] = 25.9
A.iloc[2,1] = 11.4
A.iloc[2,2] = 20

In [106]:
A

                    Caso  f_bistable  f_flutter  U_bistable  U_flutter
0                   Full        11.9       16.3         0.0        0.0
1  Segmented rectangular        16.6       25.9         0.0        0.0
2   Segmented Triangular        11.4       20.0         0.0        0.0

In [274]:

#identificacion de ensayos
dirlist = np.sort(glob.glob('/home/juan/data/balseiro/*'))
dirlist = np.array([list_i.split('/')[-1]  for list_i in dirlist])
dictfiles = {'measurement':dirlist,'folder name':dirlist}
styles = [dict(selector="caption",
                       props=[("text-align", "center"),
                              ("font-size", "150%"),
                              ("color", 'green') ])]

B = pd.DataFrame.from_dict(dictfiles)
B = B.drop(range(16))
B = B.reset_index(drop=True)
C = B.copy()
C = C.drop(range(15))
C = C.reset_index(drop=True)
#C = C.drop(range(15,27))
B.iloc[0,0] = 'Segmented rect - 0 - Reference 1'
B.iloc[1,0] = 'Segmented rect - 17.2 - Mode 0'
B.iloc[2,0] = 'Segmented rect - 17.2 - Mode 0 - b'
B.iloc[3,0] = 'Segmented rect - 17.2 - Mode 1'
B.iloc[4,0] = 'Segmented rect - 16.9 - Mode 1'
B.iloc[5,0] = 'Full  - 13.4 - Mode 1'
B.iloc[6,0] = 'Full  - 13.4 - Mode 0'
B.iloc[7,0] = 'Full  - 0 - Reference 1'
B.iloc[8,0] = 'Full  - 17.2 - Mode 1'
B.iloc[9,0] = 'Full  - 0 - Reference 2'
B.iloc[10,0] = 'Segmented triang - 13.4 - Mode 0'
B.iloc[11,0] = 'Segmented triang - 13.4 - Mode 1'
B.iloc[12,0] = 'Segmented triang - 17.2 - Mode 1'
B.iloc[13,0] = 'Segmented triang - 0 - Reference 1'
B = B.drop(range(14,42))
display(B.style.set_caption("Resumen medidas 3D").set_table_styles(styles))

In [275]:
C.iloc[0:10,0] = 'full'
C.iloc[10:15,0] = 'rect'
C.iloc[15:17,0] = 'full'
C.iloc[17:,0] = 'triang'
freqs1 = np.arange(20.,12,-1)
freqs1 = np.hstack((freqs1,[12.8,12.2]))
freqs2 = np.arange(20.,15,-1)
freqs3 = np.arange(20,11,-1)
freqs3 = np.hstack((freqs3,[11.5]))
freqs = np.hstack((freqs1,freqs2,[17.2,13.4],freqs3))
C['freq motor'] = freqs

In [272]:
C

      caso                   folder  freq motor
0     full  vid_2025-02-24_19-34-14        20.0
1     full  vid_2025-02-24_19-36-28        19.0
2     full  vid_2025-02-24_19-40-24        18.0
3     full  vid_2025-02-24_19-42-47        17.0
4     full  vid_2025-02-24_19-45-21        16.0
5     full  vid_2025-02-24_19-48-30        15.0
6     full  vid_2025-02-24_19-52-25        14.0
7     full  vid_2025-02-24_19-55-09        13.0
8     full  vid_2025-02-24_19-58-59        12.8
9     full  vid_2025-02-24_20-02-35        12.2
10    rect  vid_2025-02-24_20-06-35        20.0
11    rect  vid_2025-02-24_20-12-38        19.0
12    rect  vid_2025-02-24_20-16-35        18.0
13    rect  vid_2025-02-24_20-20-52        17.0
14    rect  vid_2025-02-24_20-37-03        16.0
15    full  vid_2025-02-25_16-17-27        17.2
16    full  vid_2025-02-25_16-28-53        13.4
17  triang  vid_2025-02-25_17-17-38        20.0
18  triang  vid_2025-02-25_17-49-41        19.0
19  triang  vid_2025-02-25_17-53-08        18.0
20  triang  vid_2025-02-25_17-56-42        17.0
21  triang  vid_2025-02-25_17-59-35        16.0
22  triang  vid_2025-02-25_18-02-42        15.0
23  triang  vid_2025-02-25_18-06-48        14.0
24  triang  vid_2025-02-25_18-11-50        13.0
25  triang  vid_2025-02-25_18-14-54        12.0
26  triang  vid_2025-02-25_18-24-10        11.5